library(dplyr)
library(DT)
library(ggrepel)
library(feather)
library(igraph)
library(networkD3)
library(readr)
library(shiny)
library(stringi)
library(tidyr)
library(threejs)
library(visNetwork)
cur_file <- file.path('data','continent-all-periods-scored.parquet')

rels <- arrow::read_parquet(cur_file) 
tmp <- filter(rels, year == "2009-11")
